export const getStepConfig = (t: any) => [
  { key: "CREATED", title: t.jobtrackingpage.steps.bookingConfirmed },
  { key: "WORKER_ACCEPTED", title: t.jobtrackingpage.steps.workeraccepted },
  { key: "WORK_STARTED", title: t.jobtrackingpage.steps.workStarted },
  { key: "IN_PROGRESS", title: t.jobtrackingpage.steps.inProgress },
  { key: "WORK_COMPLETED_BY_WORKER", title: t.jobtrackingpage.steps.completedByWorker },
  { key: "WORK_COMPLETED_PENDING", title: t.jobtrackingpage.steps.waitingCompletionOtp },
  { key: "INVOICE_GENERATED", title: t.jobtrackingpage.steps.invoiceGenerated },
  { key: "PAYMENT_PENDING", title: t.jobtrackingpage.steps.paymentPending },
  { key: "PAID", title: t.jobtrackingpage.steps.paymentDone },
  { key: "COMPLETED", title: t.jobtrackingpage.steps.completed },
  { key: "WORKER_CANCELLED", title: t.jobtrackingpage.steps.cancelledByProfessional },
  { key: "CUSTOMER_CANCELLED", title: t.jobtrackingpage.steps.cancelledByYou },
  { key: "EXPIRED", title: t.jobtrackingpage.steps.expired },
];