export const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight:      "100vh",
    background:     "#F8FAFF",
    display:        "flex",
    alignItems:     "flex-start",
    justifyContent: "center",
    padding:        "2rem 1rem",
    fontFamily:     "Inter, system-ui, sans-serif",
  },
  centeredPage: {
    minHeight:      "100vh",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
  },
  ghostBtn: {
    padding:      "12px 24px",
    border:       "1px solid #E2E8F0",
    borderRadius: 12,
    background:   "#fff",
    cursor:       "pointer",
    fontSize:     14,
    color:        "#374151",
  },
  shell: {
    width:         "100%",
    maxWidth:      860,
    background:    "#fff",
    borderRadius:  20,
    border:        "0.5px solid #E2E8F0",
    overflow:      "hidden",
    display:       "grid",
    gridTemplateColumns: "clamp(260px, 38%, 340px) 1fr",
  },
  /* left panel */
  panelLeft: {
    background:    "linear-gradient(160deg, #EEF2FF 0%, #E0E7FF 50%, #EDE9FE 100%)",
    color:         "#1E1B4B",
    padding:       "2rem",
    display:       "flex",
    flexDirection: "column",
    gap:           "1.5rem",
    borderRight:   "0.5px solid #C7D2FE",
  },
  secureBadge: {
    display:       "inline-flex",
    alignItems:    "center",
    gap:           6,
    fontSize:      11,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color:         "#6366F1",
    background:    "rgba(99,102,241,0.08)",
    padding:       "5px 10px",
    borderRadius:  20,
    width:         "fit-content",
  },
  leftLabel: {
    fontSize:      11,
    letterSpacing: "0.07em",
    textTransform: "uppercase" as const,
    color:         "#6366F1",
    marginBottom:  6,
    fontWeight:    600,
  },
  serviceName: {
    fontSize:   17,
    fontWeight: 600,
    color:      "#1E1B4B",
    lineHeight: 1.4,
  },
  bookingId: {
    fontSize:   12,
    color:      "#818CF8",
    marginTop:  4,
    fontFamily: "monospace",
  },
  divider: {
    height:     "0.5px",
    background: "rgba(99,102,241,0.15)",
  },
  priceAmount: {
    fontSize:      42,
    fontWeight:    600,
    color:         "#312E81",
    letterSpacing: "-0.02em",
    lineHeight:    1,
    marginTop:     8,
  },
  priceCurrency: {
    fontSize:      18,
    fontWeight:    400,
    color:         "#6366F1",
    marginRight:   4,
    verticalAlign: "super",
  },
  lineItems: {
    display:       "flex",
    flexDirection: "column",
    gap:           10,
  },
  securityNote: {
    marginTop:    "auto",
    display:      "flex",
    alignItems:   "flex-start",
    gap:          10,
    padding:      12,
    background:   "rgba(255,255,255,0.5)",
    borderRadius: 10,
    border:       "0.5px solid rgba(99,102,241,0.2)",
  },
  securityText: {
    fontSize:   12,
    color:      "#4338CA",
    lineHeight: 1.5,
  },
  /* right panel */
  panelRight: {
    padding:       "2rem",
    display:       "flex",
    flexDirection: "column",
    gap:           "1.25rem",
  },
  sectionTitle: {
    fontSize:      12,
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
    color:         "#6B7280",
    fontWeight:    500,
  },
  spinnerWrap: {
    display:        "flex",
    justifyContent: "center",
    padding:        "2rem 0",
  },
  methodsGrid: {
    display:             "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap:                 10,
  },
  methodBtn: {
    border:        "0.5px solid #E2E8F0",
    borderRadius:  14,
    padding:       "16px 10px",
    background:    "#fff",
    cursor:        "pointer",
    display:       "flex",
    flexDirection: "column",
    alignItems:    "center",
    gap:           8,
    position:      "relative",
    transition:    "border-color 0.15s, background 0.15s",
  },
  methodBtnSelected: {
    border:     "1.5px solid #3B82F6",
    background: "#EFF6FF",
  },
  selectedCheck: {
    position:       "absolute",
    top:            8,
    right:          8,
    width:          18,
    height:         18,
    background:     "#3B82F6",
    borderRadius:   "50%",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
  },
  methodIcon: {
    width:          40,
    height:         40,
    borderRadius:   10,
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
  },
  methodLabel: {
    fontSize:   12,
    fontWeight: 500,
    color:      "#374151",
    textAlign:  "center",
  },
  /* card fields */
  cardFields: {
    display:       "flex",
    flexDirection: "column",
    gap:           10,
  },
  fieldGroup: {
    display:       "flex",
    flexDirection: "column",
    gap:           4,
  },
  fieldLabel: {
    fontSize: 12,
    color:    "#6B7280",
  },
  cardInputWrap: {
    display:     "flex",
    alignItems:  "center",
    border:      "0.5px solid #D1D5DB",
    borderRadius: 10,
    padding:     "0 12px",
    height:      44,
    gap:         8,
    background:  "#fff",
  },
  cardInput: {
    border:      "none",
    outline:     "none",
    background:  "transparent",
    fontSize:    14,
    color:       "#111827",
    flex:        1,
    fontFamily:  "monospace",
  },
  twoCol: {
    display:             "grid",
    gridTemplateColumns: "1fr 1fr",
    gap:                 10,
  },
  plainInput: {
    height:       44,
    border:       "0.5px solid #D1D5DB",
    borderRadius: 10,
    padding:      "0 12px",
    fontSize:     14,
    color:        "#111827",
    background:   "#fff",
    outline:      "none",
    fontFamily:   "monospace",
    width:        "100%",
  },
  /* pay button */
 payBtn: {
  width: "100%",
  padding: "14px",
  background: "#10B981",
  color: "#fff",
  border: "none",
  borderRadius: 14,
  fontSize: 15,
  fontWeight: 500,
  cursor: "pointer",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
  letterSpacing: "0.01em",
  flexDirection: "row",
  flexWrap: "nowrap",
  whiteSpace: "nowrap",
},
  payBtnDisabled: {
    background: "#E5E7EB",
    color:      "#9CA3AF",
    cursor:     "not-allowed",
  },
  footerNote: {
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    gap:            6,
    fontSize:       12,
    color:          "#9CA3AF",
  },
};